services:
  back:
    build: .
    container_name: back
    restart: always
    ports:
      - "8000:8000"
    environment:
      TYPE: ${TYPE}
      PROJECT_ID: ${PROJECT_ID}
      PROJECT_KEY_ID: ${PROJECT_KEY_ID}
      PRIVATE_KEY: ${PRIVATE_KEY}
      CLIENT_EMAIL: ${CLIENT_EMAIL}
      CLIENT_ID: ${CLIENT_ID}
      AUTH_URI: ${AUTH_URI}
      TOKEN_URI: ${TOKEN_URI}
      AUTH_PROVIDER_X509_CERT_URL: ${AUTH_PROVIDER_X509_CERT_URL}
      CLIENT_X509_CERT_URL: ${CLIENT_X509_CERT_URL}
      UNIVERSE_DOMAIN: ${UNIVERSE_DOMAIN}
