services:
  back:
    build: .
    container_name: back
    restart: always
    ports:
      - "8000:8000"
    environment:
      API_PORT: ${API_PORT}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_CREDENTIALS_FILE: ${FIREBASE_CREDENTIALS_FILE}

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt # for SSL certs
    depends_on:
      - back
