services:
  back:
    build: .
    container_name: back
    restart: always
    ports:
      - "8000:8000"
    environment:
      API_PORT: ${API_PORT}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_CREDENTIALS_FILE: ${FIREBASE_CREDENTIALS_FILE}
