name: Deploy font-super job

on:
  workflow_call:
    secrets:
      SPOR_VM_SSH_KEY:
        required: true
      SPOR_VM_USER:
        required: true
      SPOR_VM_IP:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SPOR_VM_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.SPOR_VM_IP }}" >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SPOR_VM_USER }}@${{ secrets.SPOR_VM_IP }} << 'EOF'
            cd test-gcp
            git pull origin main-front-super
            cd hack-front-super
            sudo docker compose down
            sudo docker compose up -d --build
          EOF
